version: '3.8'

services:
  api:
    build:
      context: ../
      dockerfile: ./docker-setup/php/Dockerfile
    container_name: ${API_CONTAINER_NAME:-api}
    volumes:
      - ../emr-php:/var/www/html # Mount local PHP code to the container for dev only
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - db
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s

  webserver:
    image: nginx:stable-alpine
    container_name: ${WEBSERVER_CONTAINER_NAME:-api-web}
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./nginx/api.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/www.conf/:/etc/nginx/conf.d/default.conf

    restart: unless-stopped  
    networks:
      - app-network
    depends_on:
      - api

  db:
    image: mysql:5.7
    container_name: ${DB_CONTAINER_NAME:-api-db}
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
      
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

    networks:
      - app-network

  redis:
    image: redis:6-alpine
    container_name: ${REDIS_CONTAINER_NAME:-api-redis}
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "${REDIS_PORT:-6379}:6379"

  queue-worker:
    build:
      context: ../
      dockerfile: ./docker-setup/php/Dockerfile
    container_name: ${WORKER_CONTAINER_NAME:-api-worker}
    command: php /var/www/html/artisan queue:work --sleep=3 --tries=3 --queue=high,default,emails,low
    depends_on:
      - db
      - redis
    volumes:
      - ../emr-php:/var/www/html # Mount local PHP code to the container for dev only
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PHPMYADMIN_CONTAINER_NAME:-api-phpmyadmin}
    restart: unless-stopped
    environment:
      PMA_HOST: ${PMA_HOST:-db}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    networks:
      - app-network

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
